Repository wecode-bootcamp-korea/46-1st-WePet-frontend, pull requests merged in 2023-06, with the labels that each got.

#6 [46기 김지연] ADD: Footer 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/footerData.js
  src/index.js
  src/styles/common.scss
Labels: 수정 요청

#2 [46기 조수진] ADD : 회원가입 레이아웃 구현
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/TermsList.js
  src/pages/SignUp/TermsList.scss
  src/pages/SignUp/termsBox.js
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#4 [46기 조수진] ADD : 상품 카테고리 페이지 레이아웃 구현
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#12 [46기 김지연] Footer 로고 => img
  public/images/LogoBlack.png
  public/images/LogoWhite.png
  public/images/LogoYellow.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#3 [46기 조수진] ADD : 로그인 레이아웃 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#9 [46기 김지연]ProductDetail 페이지 구현
  public/data/productData.json
  public/data/productDetailData.json
  public/data/reviewData.json
  public/images/강아지장난감1-1.avif
  public/images/강아지장난감1-2.avif
  public/images/강아지장난감1-3.avif
  public/images/강아지장난감1-4.avif
  src/pages/ProductDetail/Component/Count.js
  src/pages/ProductDetail/Component/Count.scss
  src/pages/ProductDetail/Component/DetailInformation.js
  src/pages/ProductDetail/Component/DetailInformation.scss
  src/pages/ProductDetail/Component/GoToTop.js
  src/pages/ProductDetail/Component/GoToTop.scss
  src/pages/ProductDetail/Component/ImgCarousel.js
  src/pages/ProductDetail/Component/ImgCarousel.scss
  src/pages/ProductDetail/Component/Review.js
  src/pages/ProductDetail/Component/Review.scss
  src/pages/ProductDetail/Data/detailInformationData.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: 완료

#13 [46기 조수진] ADD: 상품 카테고리 페이지 - fetch 기능
  src/Router.js
  src/pages/Login/Login.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#14 FIX: Nav 배경색 제거
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/data/navData.js
Labels: 멘토 리뷰 요청

#15 [46기 백지율] ADD: 마이페이지 레이아웃 구현
  public/data/myPage.json
  src/Router.js
  src/pages/Main/components/Product/Product.js
  src/pages/Main/components/Slider/Slider.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
  src/pages/MyPage/component/MyPageModal.js
  src/pages/MyPage/component/MyPageModal.scss
  src/pages/MyPage/component/PageContent.js
  src/pages/MyPage/component/PageContent.scss
Labels: 멘토 리뷰 요청

#17 [46기 백지율] MODIFY: 메인/장바구니 컴포넌트 SCSS 수정
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartModal/CartModal.scss
  src/pages/Cart/Count/Count.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/Banner/Banner.scss
  src/pages/Main/components/Carousel/styles/CarouselContent.scss
  src/pages/Main/components/Product/Product.js
  src/pages/Main/components/Product/Product.scss
  src/pages/Main/components/Slider/components/SliderContent.js
  src/pages/Main/components/Slider/components/sliderContent.scss
Labels: 멘토 리뷰 요청

#21 [46기 백지율] ADD: Feature/config 추가
  src/config.js
  src/pages/Login/Login.js
  src/pages/Main/components/Product/Product.js
  src/pages/Main/components/Slider/Slider.js
  src/pages/ProductList/ProductList.js
  src/pages/SignUp/SignUp.js
Labels: 완료

#22 [46기 백지율] ADD: Main 컴포넌트 fetch 수정
  src/pages/Main/components/Product/Product.js
  src/pages/Main/components/Slider/Slider.js
Labels: 완료

#23 [46기 조수진] ADD: Productlist 컴포넌트 fetch 수정
  src/pages/Login/Login.js
  src/pages/Login/component/UserModal.js
  src/pages/ProductList/ProductList.js
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#24 ADD: NAV 기능 추가, 전체 SCSS 수정, TOKEN 및 fetch통신 확인
  src/components/Footer/Footer.scss
  src/components/Nav/Component/Modal.js
  src/components/Nav/Component/Modal.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/data/modalData.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Count/Count.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.scss
  src/pages/Main/components/Carousel/carouselImageData.js
  src/pages/Main/components/Carousel/styles/Arrows.scss
  src/pages/Main/components/Carousel/styles/CarouselContent.scss
  src/pages/Main/components/Product/Product.js
  src/pages/Main/components/Product/Product.scss
  src/pages/Main/components/Slider/Slider.js
  src/pages/Main/components/Slider/Slider.scss
  src/pages/Main/components/Slider/components/SliderContent.js
  src/pages/Main/components/Slider/components/sliderContent.scss
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
  src/pages/ProductDetail/Component/CartBtn.js
  src/pages/ProductDetail/Component/CartBtn.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.scss
Labels: 멘토 리뷰 요청

#26 [46기 조수진] MODIFY: 오류수정(useSearchParams 제거)
  src/pages/ProductList/ProductList.js
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청
